### ISSUE TITLE
Замечания по Shapes

### ISSUE THREAD

**Issue by alexey-malov** [artyom-yurin/OOP#12]
- [x] can convert to string => can BE converted to string

**Comment by alexey-malov** [comment]
- [x] Разобраться и уметь рассказать, зачем нужен виртуальный деструктор

**Comment by alexey-malov** [comment]
- [x] Устранить дублирование кода между разными классами фигур

**Comment by alexey-malov** [comment]
```c++
	SPoint m_leftTopVertex;
	SPoint m_rightBottomVertex;
	double m_width;
	double m_height;
```

- [x] поля класса связаны друг с другом. Устранить избыточные данные, которые могут быть вычислены на основе других

**Comment by alexey-malov** [comment]
```c++
	SPoint m_vertex1;
	SPoint m_vertex2;
	SPoint m_vertex3;
	double m_firstSide;
	double m_secondSide;
	double m_thirdSide;
```
- [x] аналогичное замечание

**Comment by alexey-malov** [comment]
- [x] Выделить доп. класса CShape и CSolidShape для хранения реализации кода, общего для фигур и фигур с заливкой. Устранить возможные проблемы множественного наследования

- [x] Проблемы с ромбовидным наследованием

**Comment by alexey-malov** [comment]
- [x] Классы разных фигур разнести по разным файлам

**Comment by alexey-malov** [comment]
- [x] Если исходный код класса или интерфейса целиком содержится только в заголовочном файле, то .cpp файл можно смело выпилить

**Comment by alexey-malov** [comment]
- [x] Использовать алгоритмы min_element и max_element для нахождения тел с минимальными/максимальными площадью и периметром

```c++
std::shared_ptr<CShape> GetSmallPerimeterShape(std::vector<std::shared_ptr<CShape>> const & shapes)
{
	auto minPerimeter = std::min_element(shapes.cbegin(), shapes.cend(), [](const auto & arg1, const auto & arg2) {
		return arg1->GetPerimeter() < arg2->GetPerimeter();
	});
	return *minPerimeter;
```

- [x] на пустом контейнере будет неопределенное поведение

**Comment by alexey-malov** [comment]
```c++
	for (char symbol : color)
	{
		if (symbol != 'F' &&
			symbol != 'E' &&
			symbol != 'D' &&
			symbol != 'C' &&
			symbol != 'B' &&
			symbol != 'A' &&
			symbol != '9' &&
			symbol != '8' &&
			symbol != '7' &&
			symbol != '6' &&
			symbol != '5' &&
			symbol != '4' &&
			symbol != '3' &&
			symbol != '2' &&
			symbol != '1' &&
			symbol != '0')
		{
			return false;
		}
	}
```

- [x] Используйте тот факт, что коды символов идут последовательно

- [x] Для задания цвета регистр букв значения играть не должен

**Comment by alexey-malov** [comment]
- [x] main огромен. Разбить на подфункции, упростить код

**Comment by AniSkyWorker** [comment]
- [x] класс CSolidShape порождает ромбовидное наследование, придумайте решение, чтобы наследование происходило иначе
https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D0%BC%D0%B1%D0%BE%D0%B2%D0%B8%D0%B4%D0%BD%D0%BE%D0%B5_%D0%BD%D0%B0%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
```C++
class CSolidShape
	: public virtual ISolidShape
	, public virtual CShape
```
- [x] свободные функции из ShapesFunctions.h можно вполне выделить в класс CStreamHandler, который будет отвечать за создание фигуры и работу с ними, туда же можно засунуть код из main, который определяет строку и вызывает функции для инициации каждой фигуры. По факту он будет создаваться в main, получать строку, "понимать", что за тип, и создавать фигурку, ну и выполнять различные команды с ней. 
```C++
if (command == "rectangle")
		{
			RectangleCommand(buffer, shapes);
		}
		else if (command == "triangle")
		{
			TriangleCommand(buffer, shapes);
		}
		else if (command == "circle")
		{
			CircleCommand(buffer, shapes);
		}
		else if (command == "line")
		{
			LineCommand(buffer, shapes);
		}
```
В идеале классов должно быть 2 (один(CStreamAgreagator) парсит поток и вызывает команды другого(CShapesAgreagator), которые уже выполняют действия с фигурой (через композицию)). Неплохим началом будет и первый вариант, а по поводу второго - можно подробнее проконсультироваться с Маловым.

**Comment by AniSkyWorker** [comment]
k = 0.7

**Comment by alexey-malov** [comment]
```c++
void DoSomethingWithShape(const IShape & shape)
{

}

int main()
{
	{
		CCircle circle({1, 2}, 10, "ff0000", "ffffff");
		DoSomethingWithShape(circle); //
	}

```
- [x] проблема ромбовидного наследования не устранена

**Comment by alexey-malov** [comment]
- [x] Уменьшить глубину вложенности в файле ShapeFunctions.cpp. Иногда лучше несколько return-ов

**Comment by alexey-malov** [comment]
```c++
bool CorrectColor(std::string const & color)
{
	if (color.length() != 6)
	{
		return false;
	}

	for (char symbol : color)
	{
		if (!((symbol <= 'F' && symbol >= 'A') || (symbol <= 'f' && symbol >= 'a') || (symbol <= '9' && symbol >= '0')))
		{
			return false;
		}
	}

	return true;
}
```

- [x] correct color - скореектируй цвет. IsColorCorrect. Сперва лучше проверять левую границу, а потом правую. Используй алгоритм all_of

**Comment by alexey-malov** [comment]
- [x] Вектор пусть хранит вектор IShape-ов, а не CShape-ов

**Comment by alexey-malov** [comment]
```
Enter command: help

Using:
rectangle <x value> <y value> <width> <height> <outline color> <fill color>
triangle <x1 value> <y1 value>  <x2 value> <y2 value> <x3 value> <y3 value> <out
line color> <fill color>
circle <center x value> <center y value>  <radius> <outline color> <fill color>
line <start x value> <start y value> <end x value> <end y value> <outline color>


Enter command: rectangle 10 20 30 40 ff0000 00ffff

Error vertex value
```
![image](https://cloud.githubusercontent.com/assets/6040682/21072270/b0d1d2ae-becd-11e6-981a-e1bcb03c14af.png)

- [x] покрыть тестами код создания фигур, исправить ошибки

**Comment by alexey-malov** [comment]
принято
