### ISSUE TITLE
Замечания по Лабораторной работе №1 "invert"

### ISSUE THREAD

**Issue by AniSkyWorker** [artyom-yurin/OOP#4]
- [x] необходимо переписать реализацию с std::array под статические размеры, на std::vectorstd::vector<float>. Как вижу, используя std::array  вы уже столкнулись с основной проблемой - отсутствием динамичного задания размеров, из-за этого и возникло по две функции GetDeterminant и PrintMatrix, vector использует кучу, поэтому его размер можно задавать динамически. Таким образом вам удастся избежать дублирования функций под разные размерности. Так же можно инициализировать с помощью списков инициализации, считывать, кроме того есть методы для работы с содержимым. Немножко примеров использования vector для

``` C++
#include <vector>

using namespase std;
const unsigned MATRIX_DIMENSION3 = 3;
/* unsigned (без знаковый тип - неотрицательные числа) без явного указывания типа
 по умолчанию берется int (т.е. неотрицательное целое)*/

typedef std::vector<std::vector<float>> Matrix;
void SomeFunction(...)
{
    Matrix mat(MATRIX_DIMENSION3, vector<float>(MATRIX_DIMENSION3, 0.f));
/* здесь с помощью конструктора создаем матрицу 3 на 3, проинициализированную нулями
первый аргумент размерность, 2ой - чему равны элементы(строка(столбец) размерности 3,
заполненная нулями

 проведенное выше - аналогично инициализации через список
Matrix minorMatrix = {
        {
            {0, 0, 0},
            {0, 0, 0},
            {0, 0, 0}
        }
     };
*/

/*для работы с элементами можно использовать квадратные скобки, если задали размер заранее
или методы push_back() и pop_back() для погружения и извлечения элементов из vector. для
доступа есть front() и back()*/
}
```
- [x]  вместо использования "магических чисел" 2 или 3 нужно оформить их в константы(см. пример выше) в циклах тоже самое можно вызывать метод для определения размера vector или array

``` C++
for (int i = 0; i < minor.size(); ++i)
```
- [x]  обращаться к элементам stl контейнеров через операторы или методы нужно не через переменные типа типа int, а через size_t

``` C++
for (size_t i = 0; i < minor.size(); ++i)
...
(const Matrix3 &matrix, size_t row, size_t column)
// и тд и тп
```
- [x]  вместо

``` C++
cout << "\n";
```

можно(нужно)

``` C++
cout << endl;
```
- [x]  запись вида 

``` C++
cout << fixed;
cout.precision(3);
cout << matrix[i][j] << " ";
```

заменяется на

``` C++
#include <iomanip>
cout << fixed
        << setprecision(3)
        << matrix[i][j] << " ";
```
- [x]  названия функций неправильные

``` C++
GetMatrixAlgebraicAdditions(const Matrix3 &matrix)  //получить матрично-алгебраичные дополнения (неправильно!)
GetMatrixOfAlgebraicAdditions(const Matrix3 &matrix) //получить матрицу алгебраческих дополнений
GetAlgebraicAdditionsMatrix(const Matrix3 &matrix) //получить матрицу алгебраческих дополнений (лучший вариант)

GetMinorMatrix(const Matrix3 &matrix) //получить  минорную матрицу(неправильно!)
GetMinorOfMatrix(const Matrix3 &matrix) //получить минор матрицы
GetMatrixMinor(const Matrix3 &matrix) //получить минор матрицы(лучший вариант)

//тоже самое
Matrix3 GetTransposedMatrixAlgebraicAdditions(const Matrix3 &matrix)
Matrix3 MultiplicationScalar(const Matrix3 & matrix, float scalar)

bool GetMatrix(ifstream & file, Matrix3 & matrix)
//название не соответствует возвращаемому типу и выполняемым внутри действиям
bool ReadMatrixFromFile(ifstream & file, Matrix3 & matrix)
```
- [x] функции GetTransposedMatrixAlgebraicAdditions и MultiplicationScalar,   GetMatrixAlgebraicAdditionsпереписать на циклы, абстрагировавшись от размеров матриц.
  Тоже самое и для получения определителя в GetDetirminant, для его нахождения есть алгоримты(Гаусса или рекурсивный)

**Comment by AniSkyWorker** [comment]
k = 0.6

**Comment by AniSkyWorker** [comment]
c вопросам можете писать тут или на почту holyrecycler@mail.ru

**Comment by alexey-malov** [comment]
``` c++
Matrix InvertMatrix(Matrix & matrix)
```
- матрицу следует принимать по константной ссылке

**Comment by alexey-malov** [comment]
- [ ] проверка на обратимость матрицы должна выполняться в функции invert matrix, чтобы не требовать предварительного вычисления детерминанта

**Comment by alexey-malov** [comment]
- [ ] в задании не требуется вычислять детерминант матрицы произвольного размера. Хотя было бы и желательно. Поэтому надо вставить проверки на размеры матриц, передаваемых в функцию вычисления определителя (что матрица 3*3)

**Comment by alexey-malov** [comment]
k=0,8

**Comment by AniSkyWorker** [comment]
- [ ] не исправлено последнее замечание Алексея
- [ ] внутри InvertMatrix дважды вызывается GetDeterminant3Matrix - сохраните результат после первой проверки, затем используйте
- [ ] переменные size_t l = 0;  size_t k = 0; можно так же объявлять в циклах for

``` C++
for (size_t j = 0, k = 0; j < matrix.size(); ++j)
```

**Comment by AniSkyWorker** [comment]
k = 0.9

**Comment by ortyomka** [comment]
Исправлено

**Comment by AniSkyWorker** [comment]
принято k = 1
