### ISSUE TITLE
Замечания по Лабораторной работе №1 "labyrinth"

### ISSUE THREAD

**Issue by AniSkyWorker** [artyom-yurin/OOP#5]
- [x] 

``` C++
switch (labyrinth[i][j])
            {
            case '#':
                labyrinthInt[i + 1][j + 1] = -1;
                break;
            default:
                labyrinthInt[i + 1][j + 1] = 0;
                break;
            }
```

swtich - case не нужен если всего 1 кейс данная конструкция идентична if - else
- [x]  в функции ConvertLabyrintCharToInt постоянно вычисляется сurrentNumber - 1, тогда как просто currentNumber не используется, в подобных случаях, при инициализации переменной стоит сразу вычесть единицу 
- [x] вместо двух структур отличающихся только именами Coordinates и Size лучше сделать одну - назвать Vector2u (от слова unsigned без знаковый = size_t) и поля в ней назвать x и y.
- [x] проверку 

``` C++
    if (countPoint != 2)
    {
        return false;
    }
```

лучше внести в цикл считывания, заменив != 2, на coutPoint < 2
если да, ++, нет - return false
- [x] в именах функций и переменных переполох со словом "Labyrint" потерялась h
- [x]   LabyrinthInt  labyrinthInt; двойной пробел
- [ ] выпилить лабиринт чаров и функции связанные с ним и конвертацией лабиринтов. работайте с числовым!инициализируйте его в зависимости от входных символов, проводите необходимые исчисления и  передавайте его в функцию PrintLabyrinth, где сразу будете выводить (в зависимости от циферки - символ)
- [x] void GetStartAndFinishCoordinate (название не соответствует типу функции)
- [ ] FindWayLabyrinth функция не только ищет но и делает внутри себя инициализацию и прочее. подберите другое название или вынесите в main

**Comment by AniSkyWorker** [comment]
- [ ] в 64битной конфигурации варнинги

**Comment by AniSkyWorker** [comment]
k = 0.5

**Comment by ortyomka** [comment]
Исправлено

**Comment by AniSkyWorker** [comment]
- [ ] bool FindWayLabyrinth(Labyrinth & labyrinth, const Vector2u & labyrinthSize, const Points points)
  поменяйте название на HasWayFound, передача по константному значению не имеет смысла
- [ ] структура Points - не нужны, из названия не ясно что там внутри, лучше передавать отдельно start и end 
- [ ]  100, 2, 3 и другие магические числа обернуть в константы

**Comment by AniSkyWorker** [comment]
k = 0.8

**Comment by ortyomka** [comment]
Исправлено

**Comment by AniSkyWorker** [comment]
принято, k = 1
