### ISSUE TITLE
Замечания по программе Vector

### ISSUE THREAD

**Issue by oMystique** [artyom-yurin/OOP#7]
- [x] Не стоит подключать `stdafx.h` в заголовочном файле, ровно, как и не стоит объявлять `using namespace`, ибо это может привести к конфликтам.
  `vector_functions.h` :

``` c++
#include "stdafx.h"
using namespace std;
```
- [x] Касательно того же файла. Реализацию функций нужно размещать в *.cpp файле. В *.h файлах стоит лишь декларировать (если речь не идёт про шаблонные функции, к примеру)

``` c++
vector <double> GetNumbers(istream & input)
{
    vector <double> result;
    copy(istream_iterator <double>(input), istream_iterator <double>(), back_inserter(result));
    return result;
}
```
- [x] Есть замечательный макрос `BOOST_CHECK_EQUAL`, который позволит не использовать явно оператор сравнения и сделает код более лаконичным

``` c++
        BOOST_CHECK_EQUAL(numbers, correctNumbers);
```
- [x] Стоит разбить каждый тест на подтесты

``` c++
BOOST_AUTO_TEST_CASE(Get_Numbers)
{
    {
        std::stringstream input("1 2 3 4 5");
        auto numbers = GetNumbers(input);
        const vector <double> correctNumbers = {
            1, 2, 3, 4, 5
        };
        BOOST_CHECK(numbers == correctNumbers);
    }

    {
        std::stringstream input("5 4 3 1 2 A r t e m 1 2 3");
        auto numbers = GetNumbers(input);
        const vector <double> correctNumbers = {
            5, 4, 3, 1, 2
        };
        BOOST_CHECK(numbers == correctNumbers);
    }

    {
        std::stringstream input("5 4 3 1 2 A r t e m");
        auto numbers = GetNumbers(input);
        const vector <double> correctNumbers = {
            5, 4, 3, 1, 2
        };
        BOOST_CHECK(numbers == correctNumbers);
    }

    {
        std::stringstream input("");
        auto numbers = GetNumbers(input);
        BOOST_CHECK(numbers.empty());
    }

    {
        std::stringstream input("1.01 2.31 3.12 3.1 3.4");
        auto numbers = GetNumbers(input);
        const vector <double> correctNumbers = {
            1.01, 2.31, 3.12, 3.1, 3.4
        };
        BOOST_CHECK(numbers == correctNumbers);
    }
}
```
- [x] Так же, стоит использовать log_formatter. 
  Пример корректного написания тестов можно найти в репозитории А. Малова
  https://github.com/alexey-malov/oop/blob/master/labs/lab2/task2/TrimBlanksTests/TrimBlanksTests.cpp
- Желательно в комментариях фиксировать номер выполненного варианта, если в контексте задачи варианты предусмотрены

Пока за базовую часть **k = 0.8**
За доп. часть **k = 1.0**

**Comment by ortyomka** [comment]
Исправлено

**Comment by AniSkyWorker** [comment]
- [x] это C-style у вас уже есть "#pragma once", она делает тоже самое, выпилить эти макросы:

``` C++
#ifndef VECTOR_FUNCTIONS_H
#define VECTOR_FUNCTIONS_H
...
#endif
```
- [x] ключевое слово inline не имеет смысла, т.к. компилятор c++, в данном случае, сам способен оптимизировать код и использовать функции, как инлайновые, уберите его и разделите объявление и реализацию этих функций по h и cpp соответственно
- [x] h файлы - именовать верхней вербюлюжей нотацией, подчеркивание зачастую не используется. переименуйте "vector_functions.h"

**Comment by AniSkyWorker** [comment]
пока что коэффициент прежний. k = 0.8

**Comment by AniSkyWorker** [comment]
принято k =1

**Comment by alexey-malov** [comment]
выставил баллы
