### ISSUE TITLE
Замечания по Find And Replace

### ISSUE THREAD

**Issue by alexey-malov** [artyom-yurin/OOP#9]
- [ ] Имена и структура тестов должны играть роль спецификации на тестируемую функцию или класс, а не просто перечислить ситуации, в которых вы проводите испытание класса или функции.
- Функция FindAndReplace
  - заменяет все вхождения искомой строки на строку-заменитель
  - не выполняет замену внутри замененного текста
  - не выполняет замену, если искомая строка пустая
  - не выполняет замену, если искомая строка не найдена в тексте

**Comment by alexey-malov** [comment]
- [x] Не выполнено треобование задания (обрабатывается только первая строка вместо всех строк в stdin):

> Разработайте на ее основе программу, заменяющую все вхождения искомой строки в стандартном потоке ввода на строку-заменитель и выводящую результат в стандартный поток вывода.

**Comment by ortyomka** [comment]
Исправлено

**Comment by AniSkyWorker** [comment]
- [x] именуем h и cpp файлы верхней верблюжьей нотацией 

k = 1

**Comment by alexey-malov** [comment]
выставил
